### ISSUE TITLE
Omnic Improperly Displaying Currently Playing Track

### ISSUE THREAD

**Issue by Nornec** [benrr101/WLTMRadioApi#8]
Occurred after playing several short-length songs from the album "East-West Blast Test" by Chris Dodge & Dave Witte, located in my library. !history still works as expected.

**Comment by benrr101** [comment]
Please see Dalf32/Omnic for Omnic related issues

**Comment by Nornec** [comment]
Thanks, issue replicated on the Omnic hub.
